Feat/migration guide
algolia/algoliasearch-client-ruby pull request #410
Opened 2020-09-15 14:51 UTC by DevinCodes

| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | yes

This adds a first draft of a migration guide to use during the alpha of the Ruby v2 client.

2020-09-15 15:16 UTC, chloelbn requested changes

2020-09-15 15:16 UTC, chloelbn commented on upgrade_guide.md
> +## Initialize the client
I would go with that phrasing and the `# before` / `# after` comments, so what you have to change directly pops to your eyes https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/php/#client-instantiation

2020-09-15 15:16 UTC, chloelbn commented on upgrade_guide.md
> +client = Algolia::Search::Client.new(search_config)
```suggestion
client = Algolia::Search::Client.create_with_config(search_config)
```

2020-09-15 15:16 UTC, chloelbn commented on upgrade_guide.md
> +The way you instantiate an Index from the client did not change.
use `# before` / `# after` comments

2020-09-15 15:16 UTC, chloelbn commented on upgrade_guide.md
> +For example:
use `# before` / `# after` comments

2020-09-15 15:16 UTC, chloelbn commented on upgrade_guide.md
> +## Methods
You can get some inspiration from this table https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/php/#list-of-method-signature-changes and maybe write the before/after signatures

2020-09-15 15:16 UTC, chloelbn commented on upgrade_guide.md
> +index.find_object(-> (hit) { h.yes? }, { query: '', paginate: true })
is `yes?` a method o_o?!

2020-09-15 15:16 UTC, chloelbn commented on upgrade_guide.md
> +### `list_indexes
```suggestion
### `list_indexes`
```

2020-09-15 15:16 UTC, chloelbn commented on upgrade_guide.md
> +`acl` is still the first parameter. The other parameters have been moved to the `reuqestOptions`.
```suggestion
`acl` is still the first parameter. The other parameters have been moved to the `requestOptions`.
```

2020-09-15 15:16 UTC, chloelbn commented on upgrade_guide.md
> +
Make a sub-title with `Client` and `Index`

2020-09-15 15:16 UTC, chloelbn commented on upgrade_guide.md
> +client = Algolia::Search::Client.new(search_config)
```suggestion
client = Algolia::Search::Client.create_with_config(search_config)
```

2020-09-16 07:20 UTC, DevinCodes commented on upgrade_guide.md
> +index.find_object(-> (hit) { h.yes? }, { query: '', paginate: true })
No, it was just an example 😂

2020-09-16 09:48 UTC, chloelbn requested changes

2020-09-16 09:48 UTC, chloelbn commented on upgrade_guide.md
> +user_ids = [1,2,3]
```suggestion
user_ids = ['1','2','3']
```

2020-09-16 13:05 UTC, chloelbn approved these changes

2020-09-16 13:05 UTC, merged