feat(config): add set_extra_header method
algolia/algoliasearch-client-ruby pull request #422
Opened 2020-10-05 11:27 UTC by chloelbn

| Q                 | A
| ----------------- | ----------
| Bug fix?          | no
| New feature?      | yes
| BC breaks?        | no

2020-10-05 15:52 UTC, DevinCodes requested changes
Looks good to me! However, I think there's a couple of things we need to do before this is ready to merge:
* We need to update the `.rbs` definition of `algolia_config` so that this new method is included.
* We need to update the upgrade guide in the root of this repository.
* We need to update the documentation. This has to be done in 2 locations: the upgrade guide, and the [`set_extra_header`](https://www.algolia.com/doc/api-reference/api-methods/set-extra-header/) page. I've changed the `set_extra_header` page to reflect setting the headers using `config.headers['z'] = 'y'`, but we need to document this method now.

Let me know when the first 2 points are done, and I'll approve the PR 😄

2020-10-06 09:37 UTC, chloelbn commented
@DevinCodes changes are pushed!

2020-10-09 09:20 UTC, DevinCodes requested changes

2020-10-09 09:20 UTC, DevinCodes commented on upgrade_guide.md
> +The `set_extra_header` method has been moved from the Client to the `Algolia::AlgoliaConfig` class. You have to define your extra headers on Client instantiation.
```suggestion
The `set_extra_header` method has been moved to the `Algolia::AlgoliaConfig` class. You have to define your extra headers before you instantiate the `Client`.
```

2020-10-09 09:20 UTC, DevinCodes commented on upgrade_guide.md
> +# `Algolia::Search::Config` inherits from `Algolia::AlgoliaConfig`
```suggestion
# Algolia::Search::Config inherits from Algolia::AlgoliaConfig
```

2020-10-14 08:24 UTC, DevinCodes approved these changes

2020-10-14 09:50 UTC, merged